
CREATE DATABASE quizlet_clone;
USE quizlet_clone;

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(100),
email VARCHAR(255) UNIQUE,
password VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE decks (
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255),
user_id INT,
is_ai_generated TINYINT(1) DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cards (
id INT AUTO_INCREMENT PRIMARY KEY,
deck_id INT,
question TEXT,
answer TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_stats (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT UNIQUE,
xp INT DEFAULT 0,
level INT DEFAULT 1,
quiz_played INT DEFAULT 0,
correct_answers INT DEFAULT 0,
total_answers INT DEFAULT 0,
current_streak INT DEFAULT 0,
best_streak INT DEFAULT 0,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE decks ADD CONSTRAINT fk_decks_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE cards ADD CONSTRAINT fk_cards_deck FOREIGN KEY (deck_id) REFERENCES decks(id) ON DELETE CASCADE;

INSERT INTO user_stats (user_id)
SELECT id FROM users
ON DUPLICATE KEY UPDATE user_id = user_id;
